// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkiofqufggjepbtmmaoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raW9mcXVmZ2dqZXBidG1tYW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDUwNzgsImV4cCI6MjA1ODA4MTA3OH0.G5GuXQsxMUsK8EytjVZs324nR6DOrHZYhePp421PlcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);